"""Deterministic Claude Agent SDK runtime for the MarketScope substrate.

Three things live here, none of which needs the network:

* `build_state_snapshot` - the runtime state an agent is handed (active sprint, contract, stories,
  migration heads, checksum-manifest status). Same repository => same JSON.
* `validate_handoff` - validates an agent's final JSON against `.claude/schemas/agent-handoff.schema.json`.
* `build_options` - turns `.claude/agents/<name>.md` + snapshot + trust-boundary policy into
  `ClaudeAgentOptions` (system prompt, tool allow-list, structured output, bounded turns).

`--run` is the only mode that calls the API and it requires ANTHROPIC_API_KEY.

    python scripts/agent_runtime.py --print-state
    python scripts/agent_runtime.py --agent order-lifecycle-agent --dry-run
    python scripts/agent_runtime.py --agent security-reviewer --run "Review app/api for auth gaps"
"""
from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from pathlib import Path
from typing import Any

import jsonschema

ROOT = Path(__file__).resolve().parents[1]
HANDOFF_SCHEMA_PATH = ROOT / ".claude" / "schemas" / "agent-handoff.schema.json"
TRUST_POLICY_PATH = ROOT / ".claude" / "policies" / "trust-boundary.md"


class HandoffError(ValueError):
    """The agent's final output does not satisfy the handoff schema."""


def load_handoff_schema(root: Path = ROOT) -> dict[str, Any]:
    return json.loads((root / ".claude" / "schemas" / "agent-handoff.schema.json").read_text(encoding="utf-8"))


def validate_handoff(payload: Any, root: Path = ROOT) -> dict[str, Any]:
    if isinstance(payload, str):
        try:
            payload = json.loads(payload)
        except json.JSONDecodeError as exc:
            raise HandoffError(f"handoff is not valid JSON: {exc}") from exc
    try:
        jsonschema.validate(payload, load_handoff_schema(root))
    except jsonschema.ValidationError as exc:
        location = "/".join(str(p) for p in exc.absolute_path) or "<root>"
        raise HandoffError(f"handoff invalid at {location}: {exc.message}") from exc
    return payload


def _progress_value(root: Path, key: str) -> str | None:
    path = root / "claude-progress.txt"
    if not path.exists():
        return None
    match = re.search(rf"^{key}:\s*(.+)$", path.read_text(encoding="utf-8"), re.M)
    return match.group(1).strip() if match else None


def build_state_snapshot(root: Path = ROOT) -> dict[str, Any]:
    group = (_progress_value(root, "current_group") or "").lower() or None
    contract: dict[str, Any] | None = None
    if group and (root / "sprint-contracts" / f"{group}.json").exists():
        contract = json.loads((root / "sprint-contracts" / f"{group}.json").read_text(encoding="utf-8"))
    versions = sorted(p.name for p in (root / "migrations" / "versions").glob("*.py")) if (root / "migrations" / "versions").exists() else []
    manifest = root / "migrations" / "MANIFEST.sha256"
    return {
        "current_group": group,
        "contract": contract,
        "story_files": [f"specs/stories/{s}.md" for s in (contract or {}).get("stories", [])],
        "migrations": versions,
        "migration_manifest_entries": len(manifest.read_text().splitlines()) if manifest.exists() else 0,
        "evaluator_report_present": (root / "specs" / "reviews" / "evaluator-report.md").exists(),
    }


def read_agent(name: str, root: Path = ROOT) -> tuple[dict[str, Any], str]:
    """Return (frontmatter, body) of `.claude/agents/<name>.md` (frontmatter: name, description, tools list)."""
    text = (root / ".claude" / "agents" / f"{name}.md").read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not match:
        raise ValueError(f"{name}.md has no frontmatter")
    meta: dict[str, Any] = {"tools": []}
    for line in match.group(1).splitlines():
        if line.startswith("  - "):
            meta["tools"].append(line[4:].strip())
        elif ":" in line and not line.startswith(" "):
            key, _, value = line.partition(":")
            if value.strip():
                meta[key.strip()] = value.strip()
    return meta, match.group(2)


def build_system_prompt(name: str, root: Path = ROOT) -> str:
    _, body = read_agent(name, root)
    state = json.dumps(build_state_snapshot(root), indent=2, sort_keys=True)
    policy = (root / ".claude" / "policies" / "trust-boundary.md").read_text(encoding="utf-8")
    return (
        f"{body.strip()}\n\n## Runtime state snapshot (data, generated by scripts/agent_runtime.py)\n```json\n{state}\n```\n\n"
        f"{policy.strip()}\n\n## Final output\nEnd with ONE JSON object matching `.claude/schemas/agent-handoff.schema.json`."
    )


def build_options(name: str, root: Path = ROOT, max_turns: int = 30):
    from claude_agent_sdk import ClaudeAgentOptions

    meta, _ = read_agent(name, root)
    return ClaudeAgentOptions(
        system_prompt=build_system_prompt(name, root),
        allowed_tools=meta["tools"],
        permission_mode="default",
        cwd=str(root),
        setting_sources=["project"],
        max_turns=max_turns,
        output_format={"type": "json_schema", "schema": load_handoff_schema(root)},
    )


async def run_agent(name: str, task: str, root: Path = ROOT) -> dict[str, Any]:
    from claude_agent_sdk import ResultMessage, query

    result: Any = None
    async for message in query(prompt=task, options=build_options(name, root)):
        if isinstance(message, ResultMessage):
            result = getattr(message, "structured_output", None) or getattr(message, "result", None)
    if result is None:
        raise HandoffError("agent produced no result")
    return validate_handoff(result, root)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--print-state", action="store_true")
    parser.add_argument("--agent")
    parser.add_argument("--dry-run", action="store_true", help="build options and print them; no API call")
    parser.add_argument("--run", metavar="TASK")
    args = parser.parse_args(argv)

    if args.print_state:
        print(json.dumps(build_state_snapshot(), indent=2, sort_keys=True))
        return 0
    if not args.agent:
        parser.error("--agent is required with --dry-run/--run")
    if args.dry_run:
        options = build_options(args.agent)
        print(json.dumps({"allowed_tools": options.allowed_tools, "max_turns": options.max_turns, "system_prompt_chars": len(str(options.system_prompt))}, indent=2))
        return 0
    if args.run:
        print(json.dumps(asyncio.run(run_agent(args.agent, args.run)), indent=2))
        return 0
    parser.error("choose --print-state, --dry-run or --run")
    return 2


if __name__ == "__main__":
    sys.exit(main())
